[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "node --disable-wasm-trap-handler server.js"
releaseCommand = "node scripts/db-push.js"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
